"""
VMT (Valve Material Type) Generation Utilities

Helper functions for generating Source 1 VMT material files
with proper shader parameters and texture references.
"""

import os
from typing import Optional, Dict, Any
from datetime import datetime


def generate_pbr_vmt(
    output_path: str,
    material_name: str,
    material_path: str,
    shader: str = "VertexLitGeneric",
    custom_params: Optional[Dict[str, Any]] = None
) -> bool:
    """
    Generate a VMT file with PBR-style parameters for Source 1
    
    Creates a VMT with proper Phong, envmap, and rimlight settings
    optimized for converted PBR materials.
    
    Texture channel mapping (expected):
    - {material_name}_color.vtf:
      * RGB: Base color (sRGB, with AO baked in)
      * Alpha: Metallic mask (for $blendtintbybasealpha)
    
    - {material_name}_normal.vtf:
      * RGB: Normal map (tangent space)
      * Alpha: Envmap mask (for $normalmapalphaenvmapmask)
    
    - {material_name}_phong.vtf:
      * RGB: Gloss/phong exponent (grayscale, linear)
      * Alpha: Rimlight mask (for $rimmask)
    
    Args:
        output_path: Full path to output VMT file
        material_name: Base name of the material (without extension)
        material_path: Relative path in materials folder (e.g., "models/props")
        shader: Shader type (default "VertexLitGeneric")
        custom_params: Optional dict of additional VMT parameters to include
    
    Returns:
        True if successful, False otherwise
    """
    # Build texture paths
    base_texture = f"{material_path}/{material_name}_color"
    bumpmap = f"{material_path}/{material_name}_normal"
    phong_texture = f"{material_path}/{material_name}_phong"
    
    # Default parameters for PBR-converted materials (merged with any custom overrides)
    params = {
        "\"$basetexture\"": base_texture,
        "\"$bumpmap\"": bumpmap,
        "\"$phong\"": "1",
        "\"$phongexponenttexture\"": phong_texture,
        "\"$phongboost\"": "1",
        "\"$phongexponent\"": "8",
        "\"$phongalbedotint\"": "1",
        "\"$phongfresnelranges\"": "[1 1 1]",
        "\"$rimlight\"": "1",
        "\"$rimlightboost\"": "8",
        "\"$rimmask\"": "1",
        "\"$model\"": "1",
        "\"$color\"": "[1 1 1]",
        "\"$color2\"": "[0.5 0.5 0.5]",
        "\"$blendtintbybasealpha\"": "1"
    }

    # Apply custom params as overrides/extra keys
    merged = dict(params)
    if custom_params:
        merged.update(custom_params)

    # Known keys in display order for pretty grouping
    texture_keys = [
        "\"$basetexture\"",
        "\"$bumpmap\"",
        "\"$phongexponenttexture\"",
    ]
    phong_keys = [
        "\"$phong\"",
        "\"$phongboost\"",
        "\"$phongexponent\"",
        "\"$phongalbedotint\"",
        "\"$phongfresnelranges\"",
    ]
    rimlight_keys = [
        "\"$rimlight\"",
        "\"$rimlightboost\"",
        "\"$rimmask\"",
    ]
    misc_keys = [
        "\"$model\"",
        "\"$color\"",
        "\"$color2\"",
        "\"$blendtintbybasealpha\"",
    ]
    default_order = texture_keys + phong_keys + rimlight_keys + misc_keys

    # Build VMT content with header and spacing
    header_comment = [
        f"// Generated by Source 2 Porting Kit — FakePBR VMT",
        f"// Material: {material_path}/{material_name}",
        f"// Date: {datetime.utcnow().isoformat(timespec='seconds')}Z",
        ""
    ]

    vmt_lines = header_comment + [f'"{shader}"', '{']

    def _append_param(key: str, value: Any):
        if isinstance(value, (str, float, int)):
            vmt_lines.append(f'    {key} "{value}"')
        else:
            vmt_lines.append(f'    {key} {value}')

    # Section: Textures
    vmt_lines.append("    // Textures")
    for k in texture_keys:
        if k in merged:
            _append_param(k, merged[k])

    vmt_lines.append("")
    # Section: Phong
    vmt_lines.append("    // Phong")
    for k in phong_keys:
        if k in merged:
            _append_param(k, merged[k])

    vmt_lines.append("")
    # Section: Rimlight
    vmt_lines.append("    // Rimlight")
    for k in rimlight_keys:
        if k in merged:
            _append_param(k, merged[k])

    vmt_lines.append("")
    # Section: Misc
    vmt_lines.append("    // Misc")
    for k in misc_keys:
        if k in merged:
            _append_param(k, merged[k])

    # Any custom keys not in defaults
    extra_keys = [k for k in merged.keys() if k not in default_order]
    if extra_keys:
        vmt_lines.append("")
        vmt_lines.append("    // Custom parameters")
        for k in extra_keys:
            _append_param(k, merged[k])

    vmt_lines.append('}')
    vmt_content = '\n'.join(vmt_lines) + '\n'
    
    # Write to file
    try:
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, 'w') as f:
            f.write(vmt_content)
        return True
    except Exception as e:
        print(f"[Error] Failed to write VMT file: {str(e)}")
        return False


def generate_simple_vmt(
    output_path: str,
    base_texture_path: str,
    shader: str = "VertexLitGeneric",
    params: Optional[Dict[str, Any]] = None
) -> bool:
    """
    Generate a simple VMT file with custom parameters
    
    More flexible VMT generator for non-PBR or custom materials.
    
    Args:
        output_path: Full path to output VMT file
        base_texture_path: Path to base texture (relative to materials folder)
        shader: Shader type
        params: Dict of VMT parameters
    
    Returns:
        True if successful, False otherwise
    """
    if params is None:
        params = {}
    
    # Ensure basetexture is set
    if "\"$basetexture\"" not in params:
        params["\"$basetexture\""] = base_texture_path

    # Build VMT content (with simple header and spacing)
    header_comment = [
        f"// Generated by Source 2 Porting Kit — Simple VMT",
        f"// Shader: {shader}",
        f"// Basetexture: {base_texture_path}",
        ""
    ]
    vmt_lines = header_comment + [f'"{shader}"', '{']
    vmt_lines.append("    // Parameters")
    for key, value in params.items():
        if isinstance(value, str):
            vmt_lines.append(f'    {key} "{value}"')
        else:
            vmt_lines.append(f'    {key} {value}')
    vmt_lines.append('}')
    vmt_content = '\n'.join(vmt_lines) + '\n'
    
    # Write to file
    try:
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, 'w') as f:
            f.write(vmt_content)
        return True
    except Exception as e:
        print(f"[Error] Failed to write VMT file: {str(e)}")
        return False


def generate_unlit_vmt(output_path: str, base_texture_path: str) -> bool:
    """
    Generate an unlit VMT (no lighting calculations)
    
    Useful for emissive materials, UI elements, etc.
    
    Args:
        output_path: Full path to output VMT file
        base_texture_path: Path to base texture
    
    Returns:
        True if successful, False otherwise
    """
    params = {
        "\"$basetexture\"": base_texture_path,
        "\"$model\"": "1",
        "\"$nocull\"": "1",
        "\"$selfillum\"": "1"
    }
    
    return generate_simple_vmt(output_path, base_texture_path, "UnlitGeneric", params)


def generate_transparent_vmt(
    output_path: str,
    base_texture_path: str,
    translucent: bool = True
) -> bool:
    """
    Generate a VMT for transparent/translucent materials
    
    Args:
        output_path: Full path to output VMT file
        base_texture_path: Path to base texture (should have alpha)
        translucent: True for translucent (blended), False for alpha test
    
    Returns:
        True if successful, False otherwise
    """
    params = {
        "\"$basetexture\"": base_texture_path,
        "\"$model\"": "1"
    }
    
    if translucent:
        params["\"$translucent\""] = "1"
    else:
        params["\"$alphatest\""] = "1"
        params["\"$alphatestreference\""] = "1"

    return generate_simple_vmt(output_path, base_texture_path, "VertexLitGeneric", params)


def generate_exopbr_vmt(
    output_path: str,
    material_name: str,
    material_path: str,
    *,
    basetexture_path: Optional[str] = None,
    texture1_path: Optional[str] = None,
    texture2_path: Optional[str] = None,
    texture3_path: Optional[str] = None,
    emissionscale: float = 0.0,
    parallaxscale: float = 0.0,
    alphablend: bool = False
) -> bool:
    """
    Generate a VMT for the ExoPBR screenspace_general_8tex shader.

    Shader: screenspace_general_8tex

    Texture mapping:
    - $basetexture: Color (RGB), Alpha = opacity
    - $texture1: ARM map (R=AO, G=Roughness, B=Metallic, A=Height for parallax)
    - $texture2: Normal map (DirectX Y- format, ATI2N recommended)
    - $texture3: Emission texture (RGB), enabled with $emissionscale

    Parameters:
    - $emissionscale: Enables and scales emission from $texture3
    - $blendemissionbycolor: If emission is enabled, allows tinting by vertex color
    - $parallaxscale: Enables and scales parallax occlusion from $texture1 alpha
    - $alphablend: Enables partial opacity using base texture alpha
    """

    # Default texture paths fall back to {material_path}/{material_name}_suffix
    base_tex = basetexture_path or f"{material_path}/{material_name}_base"
    tex1 = texture1_path or f"{material_path}/{material_name}_arm"
    tex2 = texture2_path or f"{material_path}/{material_name}_normal"

    lines = [
        f'"screenspace_general_8tex"',
        "{",
        f'    "$basetexture" "{base_tex}"',
        f'    "$texture1" "{tex1}"',
        f'    "$texture2" "{tex2}"',
    ]

    # Add optional $texture3 for emission
    if texture3_path:
        lines.append(f'    "$texture3" "{texture3_path}"')

    # Add emission scale if non-zero
    if emissionscale and emissionscale != 0.0:
        lines.append(f'    "$emissionscale" {emissionscale}')
        lines.append('    "$blendemissionbycolor" 1')  # Enable color tinting of emission
    
    # Add parallax scale if non-zero
    if parallaxscale and parallaxscale != 0.0:
        lines.append(f'    "$parallaxscale" {parallaxscale}')

    # Add alphablend if enabled
    if alphablend:
        lines.append('    "$alphablend" 1')

    lines.extend(
        [
            "",
            '    "$model" 1',
            '    "$cull" 1',
            "",
            '    "Proxies" {',
            "        ExoPBR {}",
            "    }",
            "}",
        ]
    )

    content = "\n".join(lines) + "\n"

    try:
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)
        return True
    except Exception as e:
        print(f"[Error] Failed to write ExoPBR VMT: {e}")
        return False
